---
# tasks file for redis
- name: install build-essential tcl
  apt: name={{item}} state=present
  with_items:
    - build-essential
    - tcl
  tags: [ 'packages' ]

- name: download redis
  get_url:
    url: "{{ redis_download_url }}"
    dest: /usr/local/src/
  when: not redis_tarball

- name: extract redis tarball
  unarchive:
    src: /usr/local/src/redis-{{ redis_version }}.tar.gz
    dest: /usr/local/src/
    creates: /usr/local/src/redis-{{ redis_version }}/Makefile
    copy: no

- name: compile redis
  command: make
  args:
    chdir: /usr/local/src/redis-{{ redis_version }}
    creates: /usr/local/src/redis-{{ redis_version }}/src/redis-server

- name: install redis
  command: make install
  args:
    chdir: /usr/local/src/redis-{{ redis_version }}


- name: create /etc/redis diretory
  file:
    path: /etc/redis
    state: directory


- name: copy redis.conf
  copy:
    src: /usr/local/src/redis-{{ redis_version }}/redis.conf
    dest: /etc/redis/
    remote_src: yes

- name: change supervised systemd in redis.conf
  replace:
    dest: /etc/redis/redis.conf
    regexp: '^supervised\sno$'
    replace: 'supervised systemd'
    backup: no

- name: change dir in redis.conf
  replace:
    dest: /etc/redis/redis.conf
    regexp: '^dir\s\.\/$'
    replace: 'dir /var/lib/redis'
    backup: no

- name: change bind in redis.conf
  replace:
    dest: /etc/redis/redis.conf
    regexp: '^bind\s127\.0\.0\.1\/$'
    replace: 'bind 172.31.0.0'
    backup: no

- name: add redis.service
  template: src=redis.service.j2 dest=/etc/systemd/system/redis.service

- name: Ensure group redis exists
  group:
    name: redis
    state: present

- name: create redis user
  user:
    name: redis
    group: redis
    createhome: no
    system: yes

- name: create redis diretory
  file:
    path: /var/lib/redis
    state: directory
    mode: 0770
    owner: redis
    group: redis

- name: enable redis autostart 
  command: systemctl enable redis

- name: start redis service
  service: name=redis state=started
