---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      tags: [ 'packages' ]

- import_playbook: control.yml
- import_playbook: redis.yml
- import_playbook: proxy.yml
- import_playbook: roshi-build.yml
- import_playbook: roshi-deploy.yml
