---
- hosts: proxy
  become: true
  gather_facts: false
  tasks:
    - name: verify nginx service
      service:
        name: nginx
        state: started

    - name: verify nginx is listening on 80
      wait_for: port=80 timeout=1
      ignore_errors: yes

- hosts: roshi
  become: true
  tasks:
    - name: Look for the roshi process
      shell: ps -ef |  grep roshi | grep -v grep
      register: process_list
      changed_when: false
      ignore_errors: yes

- hosts: redis
  become: true
  tasks:
    - name: verify redis service
      service:
        name: redis
        state: started

    - name: verify redis is listening on 6379
      wait_for: host={{ ansible_eth0.ipv4.address }} port=6379 timeout=1
      ignore_errors: yes
