---
# tasks file for roshi
- name: install web components
  apt: name={{item}} state=present
  with_items:
    - golang-go
    - jq
  tags: [ 'packages' ]

- name: add go env variable
  blockinfile:
    dest: /root/.bashrc
    block: |
      export GOPATH=$HOME/go
      export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  tags: [ 'configure' ]

- name: source bashrc
  become: no
  shell: . /root/.bashrc

- name:  copying roshi file
  copy:
    src: /src/roshi
    dest: /src/
    group: root
    owner: root
    mode: 0777


- name: add roshi-server env variable
  lineinfile:
    dest: /root/.bashrc
    line: 'export PATH=/src/roshi/roshi-server:$PATH'
    insertbefore: EOF
  tags: [ 'configure' ]

- name: add roshi-server env variable
  lineinfile:
    dest: /etc/profile
    line: 'export PATH=/src/roshi/roshi-server:$PATH'
    insertbefore: EOF
  register: task_result
  tags: [ 'bashrc' ]

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: task_result is changed
  tags: [ 'bashrc' ]

- name: wait for connection
  wait_for:
    host: 172.31.10.93
    port: 22
    delay: 15
    timeout: 60
    state: started
  tags: [ 'bashrc' ]
