---
# tasks file for roshi
- name: install web components
  apt: name={{item}} state=present
  with_items:
    - golang-go
    - jq
  tags: [ 'packages' ]

- name: add go env variable
  blockinfile:
    dest: /etc/profile
    block: |
      export GOPATH=$HOME/go
      export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  register: go_env

- name:  copying roshi file
  copy:
    src: /src/roshi
    dest: /src/
    group: root
    owner: root
    mode: 0777

- name: add roshi-server env variable
  lineinfile:
    dest: /etc/profile
    line: 'export PATH=/src/roshi/roshi-server:$PATH'
    insertbefore: EOF
  register: roshi_env

- name: reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
